# Generated by Django 2.2.2 on 2019-06-25 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.CharField(max_length=36, primary_key=True, serialize=False)),
                ('cover', models.URLField()),
                ('isbn', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
                ('published', models.DateTimeField()),
                ('publisher', models.CharField(max_length=255)),
                ('pages', models.IntegerField()),
                ('description', models.TextField()),
                ('website', models.URLField()),
                ('author', models.CharField(max_length=255)),
            ],
        ),
    ]
